// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owoaqqswracuqpzskcqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93b2FxcXN3cmFjdXFwenNrY3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjUyNjUsImV4cCI6MjA1ODcwMTI2NX0.4vIeDmWTgEO--szhIBdHUBDk8A91bXUz1EO7dVuPP9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);